import { Links } from 'components/Links'
import Head from 'next/head'
import { useSession } from 'next-auth/react'

export default function Home() {
  const { data: session, status } = useSession()

  return (
    <div>
      <Head>
        <title>Storybook with Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Click on any one of these links to see supported features in action
        </h1>
        <h2>{status === 'authenticated' ? 'Logged In' : 'Unauthenticated'}</h2>
        <Links />
      </main>
    </div>
  )
}
